ALL: 1
BanCommand: 0
CageCommand: 0
ColorCommand: 0
EnderchestCommand: 0
FlyCommand: 0
GameModeCommand: 0
HeadCommand: 0
HealCommand: 0
InvseeCommand: 0
LobbyFunction: 0
MessageCommand: 0
NickCommand: 0
PermissionCommand: 0
ProfileCommand: 0
RankCommand: 0
SBoardCommand: 0
SpeedCommand: 0
ThereCommand: 0
UnbanCommand: 0
PlayerDeathEvent: 0
PlayerJoinEvent: 0
PlayerQuitEvent: 0
PlayerChat: 0
PlayerMove: 0
PlayerInventory: 0
